name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.vscode/**'

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  smoke:
    name: 'Test (Smoke) ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout astro
        uses: actions/checkout@v3
        with:
          path: smoke/astro
      
      - name: Checkout docs
        uses: actions/checkout@v3
        with:
          repository: withastro/docs
          path: smoke/docs

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: '>=7.0.0'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies (astro)
        working-directory: smoke/astro
        run: pnpm install --no-frozen-lockfile

      - name: Build packages (astro)
        working-directory: smoke/astro
        run: pnpm run build

      - name: Install dependencies (docs)
        working-directory: smoke/docs
        run: pnpm i -D ../astro/packages/astro ../astro/packages/markdown/remark ../astro/packages/integrations/preact ../astro/packages/integrations/react ../astro/packages/integrations/sitemap

      - name: Build site (docs)
        working-directory: smoke/docs
        run: pnpm run build
