name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.vscode/**'

defaults:
  run:
    shell: bash

jobs:
  test:
    name: 'Test: ${{ matrix.os }} (node@${{ matrix.node_version }})'
    runs-on: ${{ matrix.os }}
    env:
      ASTRO_TELEMETRY_DISABLED: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [14, 16]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.1.7

      - name: Setup node@${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'

      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.19.3

      - name: Install dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm run build

      - name: Test
        run: pnpm run test:match "HTML and CSS scoped correctly"

